### PR TITLE
Don't link clients against PPX libraries

### PR DESCRIPTION
**Pull request by djs55**
The package cstruct.ppx contains helper functions for the PPX rewriter itself. Linking this code into applications makes them larger and also brings in a dependency on compiler-libs which pollutes the global module namespace with names like Types.

See https://github.com/mirage/mirage-www/pull/556

### CODE REVIEW

**Comment by yomimono** [comment]
@djs55, are you checking for this across the package universe?  If not, do you think it's likely to be widespread enough to merit doing so?  I'm asking because I have bits of shell scripts from the MirageOS 3 release which might be able to save some human time.

**Comment by djs55** [comment]
@yomimono I bet this is quite widespread -- IIRC not many oasis-using packages use the `XMETARequires` (or at least the ones I regularly work on don't). I'll do a bit of looking around now that I (think I) have a handle on the problem. If you have scripts, that would be very handy! :)

**Comment by yomimono** [comment]
I think I just found this in a non-OASIS package too: https://github.com/haesbaert/rawlink/compare/master...yomimono:cstruct-ppx-tags?expand=1

**Comment by djs55** [comment]
... and a mistake I made very recently, oops: https://github.com/mirage/shared-memory-ring/pull/33. On the plus side when I pin `shared-memory-ring`, `tcpip` and `mirage-profile`, the `mirage-www` Xen unikernel links again (*cough*)

**Comment by yomimono** [comment]
The tests are still failing with a problem building the stats page for mirage-www, but I'll post an issue over on the mirage-www repository for that rather than belaboring this PR.  Thanks, @djs55!

**Pull request merged**
