### PR TITLE
Update GitHub Actions

### PR DESCRIPTION
**Pull request by smorimoto**
https://github.com/smorimoto/mirage-tcpip/actions/runs/10027678004

### CODE REVIEW

**Comment by smorimoto** [comment]
CI failures are not related to this PR and should be fixed in subsequent PR(s).

**Comment by samoht** [comment]
The build should be fixed by https://github.com/mirage/mirage-tcpip/pull/520

**Comment by smorimoto** [comment]
I will rebase this PR when the PR is merged 🙃

**Comment by samoht** [comment]
Could you rebase on top of https://github.com/mirage/mirage-tcpip/pull/520? Thanks!

**Comment by smorimoto** [comment]
I will do that!

**Comment by smorimoto** [comment]
@samoht Done! The example build seems to be broken for unrelated reason.

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
