### PR TITLE
Remove uses of Io_page.

### PR DESCRIPTION
**Pull request by samoht**
Netif is now supposed to deal with page alignment.

### CODE REVIEW

**Comment by avsm** [comment]
What's the rationale for this change? Won't this force a copy in Netif forever?

**Comment by samoht** [comment]
Just a proposal after discussions with @hannesm and @pqwy as they thought the weird memory behaviour could maybe come from that part. Didn't change much things in practice though.

**Comment by avsm** [comment]
I think this is a bad direction to go down, since it bakes in a copy where one doesn't need to exist. By being explicit about page alignment with pages that are allocated for write, we can do zero-copy write (even if the backend in Netif currently doesnt). With this patch, all that is lost...and I'm not sure what is gained.

**Comment by samoht** [comment]
ok closing.

**Pull request closed without merging**
