### PR TITLE
Fix tcp deadlock

### PR DESCRIPTION
**Pull request by mfp**

### CODE REVIEW

**Comment by yomimono** [comment]
This seems good to me but I'd appreciate a second opinion; @hannesm ?

**Comment by yomimono** [comment]
I'm deploying this on a testing basis and will merge if it seems OK.

**Comment by djs55** [comment]
@yomimono did you have any luck with your deployment?

**Comment by yomimono** [comment]
Yes, it seems OK, so merged.  Thanks for the nudge!

**Pull request merged**
