### PR TITLE
Fast start

### PR DESCRIPTION
**Pull request by samoht**
I've rebased quickly my `fast-start` branch to master. I'm not sure it still works properly and that series of patch needs some cleanup ... but at least, we can start discuss the integration.

### CODE REVIEW

**Comment by samoht** [comment]
I've rebased against master and checked that it compiles, and I've cleaned-up the patch history. Now need to check that it still works ...

**Comment by MagnusS** [comment]
I tried to compile this with current master and got the following error:

```ocaml
#=== ERROR while installing tcpip.2.2.1 =======================================#
# opam-version 1.2.0
# os           linux
# command      make
# path         /home/mirage/.opam/system/build/tcpip.2.2.1
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/mirage/.opam/system/build/tcpip.2.2.1/tcpip-21583-e7966f.env
# stdout-file  /home/mirage/.opam/system/build/tcpip.2.2.1/tcpip-21583-e7966f.out
# stderr-file  /home/mirage/.opam/system/build/tcpip.2.2.1/tcpip-21583-e7966f.err
### stdout ###
# ...[truncated]
# /home/mirage/.opam/system/bin/ocamlfind ocamldep -package cstruct -package io-page -package ipaddr -package lwt -package mirage-types -modules channel/channel.ml > channel/channel.ml.depends
# /home/mirage/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package cstruct -package io-page -package ipaddr -package lwt -package mirage-types -I channel -o channel/channel.cmo channel/channel.ml
# + /home/mirage/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package cstruct -package io-page -package ipaddr -package lwt -package mirage-types -I channel -o channel/channel.cmo channel/channel.ml
# File "channel/channel.ml", line 137, characters 34-49:
# Error: This expression has type Io_page.t
#        but an expression was expected of type
#          Cstruct.buffer =
#            (char, Bigarray.int8_unsigned_elt, Bigarray.c_layout)
#            Bigarray.Array1.t
# Command exited with code 2.
### stderr ###
# W: Cannot find source file matching module 'tcp' in library tcp
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/libtcpip_stubs.a lib/dlltcpip_stubs.so lib/tcpip.cma lib/tcpip.cmxa lib/tcpip.a lib/tcpip.cmxs lib/libtcpip_xen_stubs.a lib/dlltcpip_xen_stubs.so lib/tcpip_xen.cma lib/tcpip_xen.cmxa lib/tcpip_xen.a lib/tcpip_xen.cmxs lib/ethif.cma lib/ethif.cmxa lib/ethif.a lib/ethif.cmxs lib/ipv4.cma lib/ipv4.cmxa lib/ipv4.a lib/ipv4.cmxs lib/ipv6.cma lib/ipv6.cmxa ...[truncated]
# make: *** [build] Error 1
```

**Comment by samoht** [comment]
which version of io_page and such are you using?

**Comment by samoht** [comment]
Hum, I cannot reproduce. Try to `opam update && opam upgrade` and report the version of your packages:

```
$ opam list --required-by tcpip --rec
# Available packages recursively required by tcpip.2.2.2 for 4.02.1:
base-bytes               base  Bytes library distributed with the OCaml compiler
camlp4               4.02.1+2  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                0.9.6  Declarative definition of command line interfaces for OCaml
cppo                    1.1.2  Equivalent of the C preprocessor for OCaml programs
cstruct                 1.5.0  access C structures via a camlp4 extension
io-page                 1.2.0  Allocate memory pages suitable for aligned I/O
ipaddr                  2.5.0  IP (and MAC) address representation library
lwt                     2.4.7  A cooperative threads library for OCaml
mirage-clock-unix       1.0.0  A Mirage-compatible Clock library for Unix
mirage-console          2.1.1  A Mirage-compatible Console library for Xen and Unix
mirage-net-unix         2.1.0  Ethernet network driver for Mirage, using tuntap
mirage-profile            0.4  Collect profiling information
mirage-types            2.2.0  Module type definitions for Mirage-compatible applications
mirage-types-lwt        2.2.0  Lwt module type definitions for Mirage-compatible applications
mirage-unix             2.2.1  Mirage OS library for Unix compilation
ocamlfind               1.5.5  A library manager for OCaml
ocplib-endian             0.8  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
optcomp                   1.6  Optional compilation with cpp-like directives
ounit                   2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
ppx_tools              0.99.2  Tools for authors of ppx rewriters and other syntactic tools
sexplib             112.06.00  Library for serializing OCaml values to and from S-expressions
shared-memory-ring      1.1.1  Shared memory rings for RPC and bytestream communications.
tuntap                  1.0.0  TUN/TAP bindings
type_conv           112.01.00  Library for building type-driven syntax extensions
```

**Comment by MagnusS** [comment]
Thanks - looks like it was an error on my end. I update/upgraded + reverted to master and reapplied the patch and now it compiles fine. 

```
$ opam list --required-by tcpip --rec
# Available packages recursively required by tcpip.2.2.1 for system:
base-bytes             legacy  Bytes compatibility library distributed with ocamlfind
base-no-ppx              base  A pseudo-library to indicate lack of extension points support
camlp4                 4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                0.9.6  Declarative definition of command line interfaces for OCaml
cppo                    1.1.2  Equivalent of the C preprocessor for OCaml programs
cstruct                 1.5.0  access C structures via a camlp4 extension
io-page                 1.4.0  Allocate memory pages suitable for aligned I/O
ipaddr                  2.5.0  IP (and MAC) address representation library
lwt                     2.4.7  A cooperative threads library for OCaml
mirage-clock-unix       1.0.0  A Mirage-compatible Clock library for Unix
mirage-console          2.1.1  A Mirage-compatible Console library for Xen and Unix
mirage-net-unix         2.1.0  Ethernet network driver for Mirage, using tuntap
mirage-profile            0.4  Collect profiling information
mirage-types            2.2.0  Module type definitions for Mirage-compatible applications
mirage-types-lwt        2.2.0  Lwt module type definitions for Mirage-compatible applications
mirage-unix             2.2.1  Mirage OS library for Unix compilation
ocamlfind               1.5.5  A library manager for OCaml
ocplib-endian             0.8  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
optcomp                   1.6  Optional compilation with cpp-like directives
ounit                   2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
sexplib             111.25.00  Library for serializing OCaml values to and from S-expressions
shared-memory-ring      1.1.1  Shared memory rings for RPC and bytestream communications.
tuntap                  1.0.0  TUN/TAP bindings
type_conv           111.13.00  Library for building type-driven syntax extensions
```

**Comment by MagnusS** [comment]
I get the following error when compiling static_website:
```
File "main.ml", line 41, characters 27-28:
Error: Signature mismatch:
       ...
       The field `of_string_exn' is required but not provided
       The field `to_string' is required but not provided
Command exited with code 2.
make: *** [main.native.o] Error 10
```

It fails on module T=...:
```ocaml
 module Stackv41 = struct
   module E = Ethif.Make(Netif)
    module I = Ipv4.Make(E)
    module U = Udp.Make(I)
    module T = Tcp.Flow.Make(I)(OS.Time)(Clock)(Random)
    module S = Tcpip_stack_direct.Make(Console)(OS.Time)(Random)(Netif)(E)(I)(U)(T)
    include S
  end
```
I get a similar error for synjitsu and for the Jitsu test unikernels. If I unpin tcpip and reinstall the latest release everything compiles.

It seems to be caused by the extended IP type in tcp/wire.ml:

```ocaml
module type IP = sig
    (* XXX: to add to the mirage-types/V1.ml/IP signature *)
    include V1_LWT.IP
    val to_string: ipaddr -> string
    val of_string_exn: string -> ipaddr
  end
```

**Comment by samoht** [comment]
@nojb how are we supposed to print/read abstract IP address with the new IP signatures? should we use sexp?

**Comment by samoht** [comment]
@MagnusS you could use something similar to https://github.com/mirage/mirage-tcpip/pull/99/files#diff-221b1cbb1e9084f2ddfd14c38908f6c1R2 in the generated code. That's not ideal though, I'm checking if there is a better way ...

**Comment by nojb** [comment]
@samoht I see two possibilities: either use `sexp` (or similar) or require the necessary functionality as a sub-signature `IPADDR` of the module type `IP`.  I was under the impression that we don't want `mirage-types` to depend on `sexplib`, right ?

**Comment by samoht** [comment]
Ideally you want to expose everything that is common in `V4` and `V6` in https://github.com/mirage/ocaml-ipaddr/blob/master/lib/ipaddr.mli#L40, but this doesn't really scale, so simplest thing might be to either have `to_string` and `of_string_exn` only, or a way to break the abstraction:

```
to_raw_ipaddr: ipaddr -> [ `V4 of Ipaddr.V4 | `V6 of Ipaddr.V6.t ]
of_raw_ipdadr: [ `V4 of Ipaddr.V4 | `V6 of Ipaddr.V6.t ] -> ipaddr option
```

**Comment by dsheets** [comment]
By the way, `Ipaddr.t` which supports V4 and V6 exists: <https://github.com/mirage/ocaml-ipaddr/blob/master/lib/ipaddr.mli#L483>.

**Comment by samoht** [comment]
that's even better. Just need some conversion to and from `V1_LWT.IP.ipaddr` to `Ipaddr.t` then in `mirage-type` then, I'll add these.

**Comment by nojb** [comment]
But note that `mirage-types` also exposes signatures `IPV4` and `IPV6` (for when you actually care which version you need), where `ipaddr` is specialized to `Ipaddr.V4.t` and, respectively, `Ipaddr.V6.t`. In that case the conversion `IP.ipaddr -> Ipaddr.t` will be losing information...

**Comment by samoht** [comment]
See https://github.com/mirage/mirage/pull/361 and https://github.com/samoht/mirage-tcpip/commit/1a624f2b6ee41b916c95aab477f9202b38c98a96

**Pull request closed without merging**
