### PR TITLE
Compatibility with lwt >= 2.7.0

### PR DESCRIPTION
**Pull request by djs55**
Lwt_unix.bind now returns a promise.

Rleated to ocsigen/lwt#308

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by yomimono** [comment]
Thanks for these patches, @djs55 !  Can you add a pin for `lwt.3.0.0` (or restate the version constraint such that the solver can find it)?

**Comment by djs55** [comment]
@yomimono ok, will do!

**Comment by yomimono** [comment]
Pushed a commit that removes the pin, since `lwt` was just merged.  The tests are still failing, but they're doing so because there's no released version of `conduit` that's compatible with `lwt` 3.0.0, and so a build of `mirage-www` can't succeed.  Since you have a pull request in there, I'm OK with the test failures; if `conduit` goes a while without a release compatible with `lwt` 3.0.0, we can pin it here.

**Comment by aantron** [comment]
@djs55: you can use `Lwt_unix.Versioned.bind_1` to use the old API and be compatible with Lwt 2.7.0+, or `Lwt_unix.Versioned.bind_2` to use the new API and also still be compatible with Lwt 2.7.0+. Switching hard to Lwt 3.0.0 is likely to be painful, hence the availability of these versioned names. I know I've already mentioned such things in other issues on other repos, so I apologize – this is in part for the benefit of other readers (@yomimono :) ).

**Comment by djs55** [comment]
I switched to the versioned interface and used `bind_2` for `lwt { >= 2.7.0 }`. One of the revdeps failed:
```
The following dependencies couldn't be met:
  - mirage-unikernel-www-unix[33m -> [mcowabloga[33m -> [mlwt < 2.7.0
  - mirage-unikernel-www-unix[33m -> [mcowabloga[33m -> [mcohttp = 0.10.0[33m -> [msexplib < 113.01.00
  - mirage-unikernel-www-unix[33m -> [mmirage-types-lwt >= 3.0.0[33m -> [mmirage-channel-lwt >= 3.0.0[33m -> [mlwt >= 2.4.7
  - mirage-unikernel-www-unix[33m -> [mtcpip >= 3.1.0[33m -> [mlwt >= 2.7.0
Your request can't be satisfied:
  - Conflicting version constraints for lwt
```
I'll investigate `cowabloga`.

**Comment by djs55** [comment]
I've released an updated `cowabloga`: https://github.com/ocaml/opam-repository/pull/9168

**Comment by djs55** [comment]
CI is now green. I'll remove the `EXTRA_REMOTES` when the `cowabloga` PR is merged.

**Pull request merged**
