### PR TITLE
Prepare the release

### PR DESCRIPTION
**Pull request by samoht**
@talex5 @yomimono and @MagnusS can you check that you are happy with the change notes?

### CODE REVIEW

**Comment by talex5** [comment]
OK with me (though it's not exactly a "dead-lock" - it's just very slow).

**Comment by hannesm** [comment]
splitting out channel into a separate repository is not worth mentioning in changes?

**Comment by yomimono** [comment]
Text looks OK but we should remove the channel tests (and surely the dependency?) as well.

**Comment by MagnusS** [comment]
@MagnusS not @MagnusM :-) and Balraj also helped on #157

**Comment by yomimono** [comment]
yaaaaaay! \o/

**Pull request merged**
