### PR TITLE
check length of received ethernet frame (to avoid cstruct exceptions)

### PR DESCRIPTION
**Pull request by hannesm**
provide ethertype_to_protocol / protocol_to_ethertype conversion
cleanup code

should be straightforward. please let me know if you consider this code to be less readable

### CODE REVIEW

**Comment by mor1** [comment]
looks good to me, assuming travis passes.

is there a reason not to use Cstruct's `cenum` to declare the constants and associated convertors in `wire_structs.ml`?  cf. eg., <https://github.com/mirage/ocaml-dns/blob/master/lib/packet.ml>

**Comment by hannesm** [comment]
cenum produces variants -- thus they need to be qualified -- whereas I use polyvars here.. I'm still not decided what the best way [tm] to do this is... most likely will switch over to cenum and variants, for the simple sake of speed...

**Comment by hannesm** [comment]
@mor1 see 2499b57 :)

**Comment by mor1** [comment]
cool :)

**Comment by hannesm** [comment]
hmm, actually I like 1e3e291 much better.. what do you think? separating the parser out (should actually go into a different module than Wire_structs, shouldn't it?)

**Comment by mor1** [comment]
tbh i think there's some general stuff to do about cleaning up parsing in all our protocol stacks, cf discussions about CPS with @pqwy. certainly separating parsing from input processing makes sense to me (and would probably allow eg `pcap-format` to more easily reuse it too).

**Comment by hannesm** [comment]
yes, this is a start. we can rewrite it later, once we know how the generic parsing interface should look like..

**Comment by samoht** [comment]
I like it

**Comment by hannesm** [comment]
ping? any opinion (this change should be straightforward, and not change semantics)

**Comment by samoht** [comment]
Can you rebase your patch? I'm happy to merge once done.

**Comment by hannesm** [comment]
rebased

**Comment by samoht** [comment]
Hum, the ARP tests are not working very well with your changes ...

**Comment by hannesm** [comment]
`parse_ethernet_frame` is now more picky, it requires each packet to be at least 60 bytes in size (as [specified here](https://en.wikipedia.org/wiki/Ethernet_frame)).  Our ARP implementation does not pad frames to that size, but sends out ethernet frames of size 42 (and relies on the NIC to pad).

It seems to be sensible to let the NIC pad the data, thus I relaxed the check in 26c9311.

**Comment by hannesm** [comment]
@samoht now travis is happy and the tests are passing

**Comment by samoht** [comment]
Great, thanks!

**Pull request merged**
