### PR TITLE
Add optional arguments for settings in ip v6 and v4 connects

### PR DESCRIPTION
**Pull request by Drup**
This simplifies the code a bit in the mirage dsl and it should be useful in general.

### CODE REVIEW

**Comment by avsm** [comment]
Fine by me, but could you add ocamldoc to indicate what the default values are for that function?

**Comment by Drup** [comment]
I can do it for ipv4, but for ipv6, I have no idea what the defaults are. When an argument is not present, I just don't set it.

**Comment by Drup** [comment]
Should I add a default value ? I must admit that I basically don't understand the rest of the file.

**Comment by samoht** [comment]
thanks!

**Pull request merged**
