### PR TITLE
Ensure that a call of listen really binds the given socket to the INET_ADDR

### PR DESCRIPTION
**Pull request by dinosaure**
It's a simple fix for #438

### CODE REVIEW

**Comment by hannesm** [comment]
this looks fine, but there are two other occasions of similar code in the same module -- would you mind to adapt them accordingly?

also, ocaml-ci complains (rightfully):
```
tcpip.opam: changes needed:
  "ppx_cstruct"
```
could you make this change as well, please. thanks.

**Comment by hannesm** [comment]
(pushed the requested changes to your branch directly)

**Comment by dinosaure** [comment]
I'm ok with updates :+1: thanks!

**Comment by hannesm** [comment]
hmm, the error (on travis with 4.08) is unexpected, anyone encountered this before (/cc @mirage/core)?

```bash
ld: /home/opam/.opam/4.08/lib/pkgconfig/../../lib/ocaml-freestanding/libasmrun.a(startup_aux_n.o):/home/opam/.opam/4.08/.opam-switch/build/ocaml-freestanding.0.6.3/ocaml/runtime/startup_aux.c:35: multiple definition of `caml_atom_table'; /home/opam/.opam/4.08/lib/pkgconfig/../../lib/ocaml-freestanding/libasmrun.a(startup_nat_n.o):/home/opam/.opam/4.08/.opam-switch/build/ocaml-freestanding.0.6.3/ocaml/runtime/startup_nat.c:47: first defined here

run ['ld' '-nostdlib' '-z' 'max-page-size=0x1000' '-static' '-T'
     '/home/opam/.opam/4.08/lib/pkgconfig/../../lib/solo5-bindings-xen/solo5_xen.lds'
     '/home/opam/.opam/4.08/lib/pkgconfig/../../lib/solo5-bindings-xen/solo5_xen.o'
     '_build/main.native.o' '_build/manifest.o'
     '-L/home/opam/.opam/4.08/lib/mirage-crypto'
     '-l:libmirage_crypto_freestanding_stubs.a'
     '/home/opam/.opam/4.08/lib/pkgconfig/../../lib/mirage-xen/libmirage-xen_bindings.a'
     '-L/home/opam/.opam/4.08/lib/pkgconfig/../../lib/ocaml-freestanding'
     '-lasmrun' '-lnolibc' '-lopenlibm' '-o' 'services.xen']: exited with 1
```

**Comment by dinosaure** [comment]
I never got this error but I never used `xen` backend.

**Comment by dinosaure** [comment]
I think the error is related to #441 where we miss something about Xen C stubs which implements checksum. An easier proposal is to delete `xen_linkopts = "-L@tcpip/xen -ltcpip_xen_stubs"` I think. It's probably the best solution when the Xen backend use `ocaml-freestanding` now. WDYT?

**Comment by hannesm** [comment]
@dinosaure good point, I pushed a commit here to remove the META template here (I forgot to do this in #434).

**Comment by dinosaure** [comment]
According to https://github.com/mirage/ocaml-freestanding/pull/88#issuecomment-789574485, the error on the CI is about 4.08.0 but we will delete the support of it on the CI. I think it's ok to merge. I will prepare a small PR to delete the support of 4.08.0 and upgrade `ocamlformat` to get a green CI.

**Pull request merged**
