### PR TITLE
Ipv6 cleanup

### PR DESCRIPTION
**Pull request by nojb**
I was sitting on this cleanup for a long time without time to get it into shape.

There are no external changes to the lwt interface.

The logic is essentially unchanged but with a fair amount of code reorganisation, simplification, etc.  I think it will help to whoever wants to hack on this.  Also I added a proper signature with some comments.

### CODE REVIEW

**Comment by hannesm** [comment]
what is the status of this PR? should we merge it, considering that nobody apart from @nojb really used the v6 stuff (and according to him, this PR improves on readability).

**Comment by nojb** [comment]
This PR can be merged as it is - it improves quite a bit the organization of the code and general readability so I don't see any downsides to merging ...

**Comment by hannesm** [comment]
@djs55 @samoht @avsm @yomimono @talex5 anything against merging this PR?

**Comment by avsm** [comment]
Fine with this -- we need to integrate IPv6 properly via Functoria's config interface, so the latest version in trunk is best.  No consumers of this yet as far as I know.

**Pull request merged**
