### PR TITLE
improve tcp options marshalling/unmarshalling

### PR DESCRIPTION
**Pull request by yomimono**
This PR includes some tests for TCP options marshalling and unmarshalling, as well as some changes to make them pass.  Among cases addressed are the problems in #106 .

### CODE REVIEW

**Comment by samoht** [comment]
tests! yay!

**Comment by yomimono** [comment]
Whoops, fails on 4.01; I'll fix.

**Comment by hannesm** [comment]
you might also want to increase the cstruct version requirement to 1.6.0 (when memset got introduced)

**Comment by yomimono** [comment]
Good catch, thanks!

**Comment by hannesm** [comment]
I read through this PR, and think it is a great improvement of TCP option parsing (I consulted RFC793 to look whether those conform, and they do!)!

**Comment by yomimono** [comment]
...ping?  It would be nice to have this merged.

**Comment by mor1** [comment]
Indeed yes-- thanks!

**Comment by yomimono** [comment]
Thanks @mor1 !

**Pull request merged**
