### PR TITLE
Fix the ICMP socket test on Windows

### PR DESCRIPTION
**Pull request by djs55**
This patch works around some Windows-isms which currently leak through the lower-level libraries:

- Windows uses `SOCK_RAW` for ICMP sockets whereas Unix uses `SOCK_DGRAM`
- `Lwt` on Windows doesn't implement `Lwt_bytes.{recvfrom,sendto}`

At module load time we compute `Sys.os_type = "Win32"` and then use this to select between Unix and Windows.

Ideally these minor differences would be abstracted away by the lower-level libraries.

Fixes the specific case mentioned in #331 although there is still another failing test.

### CODE REVIEW

**Comment by yomimono** [comment]
This looks good to me.  Out of curiosity, does Windows allow unprivileged ICMP sockets?

**Comment by djs55** [comment]
Dunno -- I didn't look very closely. It would be interesting to find out though... I'll have a play when I'm next in front of a Windows machine.

**Comment by djs55** [comment]
Thinking about it, when I ran this test it was as a regular user I think. Interesting!

**Comment by djs55** [comment]
I've made a simple `ping` CLI tool (based on the code in the ICMP test case) and it runs as an unprivileged user on both Mac and Windows (on Linux I always get `EACCES` even as root -- not sure what's going on there).

Windows just worked (to my surprise!) but the Mac kernel seems to return an IP datagram with an over-large length (16384). I guess this reflects some kind of maximum theoretical size / kernel buffer size rather than the actual on-the-wire size. Seems a bit buggy; I'll have to work around it somewhere.

I was also surprised that a whole IP datagram was returned, rather than only the ICMP portion. This is useful though for things like the `ttl` so that's good I guess...

I'll make a PR with the example soon.

**Comment by yomimono** [comment]
It's probably worth documenting that you get the whole packet, that's surprising (and I'm not sure intended?)

**Pull request merged**
