### PR TITLE
Add vnetif backend with uniform packet loss and new iperf test

### PR DESCRIPTION
**Pull request by MagnusS**
Adds a new vnetif backend + iperf test that drops 1% of sent packets

### CODE REVIEW

**Comment by avsm** [comment]
very useful!

**Comment by MagnusS** [comment]
Hm! One of the travis tests failed again - not sure why. I've enabled verbose test output in `opam` with -v. It would be better to use --show-errors, but it's not available in ocaml < 4.02

**Comment by MagnusS** [comment]
Travis tests are passing now, so I guess it must have been a temporary problem.

**Comment by samoht** [comment]
Nice!

**Pull request merged**
