### PR TITLE
adjust assert to allow trailing bytes

### PR DESCRIPTION
**Pull request by hannesm**
see issue https://github.com/mirage/mirage-net-xen/issues/24

### CODE REVIEW

**Comment by avsm** [comment]
@samoht it's now very hard to release tcpip since you seem to have the lock on it and have had it for a while... what needs to happen to merge this and unbreak ARM?

**Comment by avsm** [comment]
This one needs to merge, but I think it shouldn't be an assert.  We should raise a proper exception or use some other functional callback to indicate we dropped the packet (in fact, the latter would be good: a `?drop_action` that would be a logger or just an identity function to discard it)

**Comment by hannesm** [comment]
I think due to it being very partial (there are lots of other potential out-of-bounds accesses, such as the split a few lines above), the assert can just be dropped. It would be good to have an interface which does not throw exceptions in a future tcp/ip release.

**Comment by hannesm** [comment]
@samoht @avsm if you want to release TCP/IP + mirage, I'd be happy to back out https://github.com/mirage/mirage/pull/390 (and wait to get conduit/tls/entropy for 2.4.7 then).

**Comment by avsm** [comment]
Let's not roll anything back. I'll cut a point release of tcpip with this fixed as a branch.

**Comment by avsm** [comment]
v2.3.1 released.  Everyone ok with a silent drop of the malformed frame in #122 instead of an assert?

**Comment by samoht** [comment]
We should at least print a debug message on the console when this happens.

**Comment by avsm** [comment]
No, we shouldn't.  All such messages need to go to some logging service and not to the console (which is a denial of service very easily).

**Comment by hannesm** [comment]
this is superseeded by changes in 2.3.1 / 2.4.1

**Pull request closed without merging**
